export const terms = [
  {name:"Abdominal distension",entity:"/m/09d7vk",alias:null},
  {name:"Abdominal obesity",entity:"/m/0f8fc",alias:null},
  {name:"Abdominal pain",entity:"/m/02tfl8",alias:null},
  {name:"Abnormal posturing",entity:"/m/08hpp7",alias:null},
  {name:"Abscess",entity:"/m/0lxt",alias:null},
  {name:"Absent-mindedness",entity:"/m/026__2h",alias:null},
  {name:"Acanthosis nigricans",entity:"/m/036b82",alias:null},
  {name:"Achilles tendon rupture",entity:"/m/06tbxm",alias:null},
  {name:"Acid erosion",entity:"/m/065tzg",alias:null},
  {name:"Acidosis",entity:"/m/02gwty",alias:null},
  {name:"Acne",entity:"/m/0jwqt",alias:null},
  {name:"Actinic keratosis",entity:"/m/04r3p5",alias:null},
  {name:"Acute Bronchitis",entity:"/m/01s2xh",alias:null},
  {name:"Acute kidney injury",entity:"/m/03545w",alias:null},
  {name:"Acute myeloid leukemia",entity:"/m/0bx3n7",alias:null},
  {name:"Adenomyosis",entity:"/m/054xgp",alias:null},
  {name:"Afterimage",entity:"/m/02h98q",alias:null},
  {name:"Ageusia",entity:"/m/05sfr2",alias:null},
  {name:"Agnosia",entity:"/m/016q5d",alias:null},
  {name:"Agonal respiration",entity:"/m/07gylr",alias:null},
  {name:"Akathisia",entity:"/m/01dzyw",alias:null},
  {name:"Albinism",entity:"/m/0122t",alias:null},
  {name:"Alcohol flush reaction",entity:"/m/05nn1b",alias:null},
  {name:"Alcoholism",entity:"/m/012jc",alias:null},
  {name:"Alice in Wonderland syndrome",entity:"/m/019szr",alias:null},
  {name:"Alkalosis",entity:"/m/02gwvb",alias:null},
  {name:"Allergic bronchopulmonary aspergillosis",entity:"/m/0cvcl5",alias:null},
  {name:"Allergic conjunctivitis",entity:"/m/04v6d0",alias:null},
  {name:"Allergy",entity:"/m/0fd23",alias:null},
  {name:"Allodynia",entity:"/m/096m74",alias:null},
  {name:"Alogia",entity:"/m/01r718",alias:null},
  {name:"Alopecia areata",entity:"/m/016q32",alias:null},
  {name:"Alpha 1-antitrypsin deficiency",entity:"/m/01t4q6",alias:null},
  {name:"Alzheimer's disease",entity:"/m/0dcsx",alias:null},
  {name:"Amaurosis",entity:"/m/05wt36",alias:null},
  {name:"Amaurosis fugax",entity:"/m/036bqx",alias:null},
  {name:"Amblyopia",entity:"/m/02s64_",alias:null},
  {name:"Amenorrhoea",entity:"/m/01j62y",alias:null},
  {name:"Amnesia",entity:"/m/01j4hd",alias:null},
  {name:"Amyotrophic lateral sclerosis",entity:"/m/017s1k",alias:null},
  {name:"Anal fissure",entity:"/m/02gscl",alias:null},
  {name:"Anaphylaxis",entity:"/m/0jtyb",alias:null},
  {name:"Anasarca",entity:"/m/036br7",alias:null},
  {name:"Androgen replacement therapy",entity:"/m/026bcwh",alias:null},
  {name:"Anemia",entity:"/m/0lcdk",alias:null},
  {name:"Anencephaly",entity:"/m/01hr6t",alias:null},
  {name:"Angina pectoris",entity:"/m/0hg45",alias:null},
  {name:"Angioedema",entity:"/m/03tlvj",alias:null},
  {name:"Angular cheilitis",entity:"/m/099686",alias:null},
  {name:"Anhedonia",entity:"/m/01nvfh",alias:null},
  {name:"Aniridia",entity:"/m/03gxt1",alias:null},
  {name:"Anisocoria",entity:"/m/08mh71",alias:null},
  {name:"Anorexia nervosa",entity:"/m/098lw",alias:"Anorexia"},
  {name:"Anosmia",entity:"/m/0m7pl",alias:null},
  {name:"Antepartum haemorrhage",entity:"/m/056x7r",alias:null},
  {name:"Anterograde amnesia",entity:"/m/02m3p2",alias:null},
  {name:"Anti-social behaviour",entity:"/m/02l4fy",alias:null},
  {name:"Antisocial personality disorder",entity:"/m/01c88f",alias:null},
  {name:"Anuria",entity:"/m/04f74cm",alias:null},
  {name:"Anxiety",entity:"/m/0k_9",alias:null},
  {name:"Apathy",entity:"/m/01y4zk",alias:null},
  {name:"Aphakia",entity:"/m/0831jw",alias:null},
  {name:"Aphasia",entity:"/m/0wnw",alias:null},
  {name:"Aphonia",entity:"/m/025s02j",alias:null},
  {name:"Apnea",entity:"/m/01mr85",alias:null},
  {name:"Apraxia",entity:"/m/0flz_",alias:null},
  {name:"Arcus senilis",entity:"/m/06stpj",alias:null},
  {name:"Arthritis",entity:"/m/0t1t",alias:null},
  {name:"Arthrogryposis",entity:"/m/0nrd_",alias:null},
  {name:"Arthropathy",entity:"/m/07nsp9",alias:null},
  {name:"Ascites",entity:"/m/01c24r",alias:null},
  {name:"Asperger syndrome",entity:"/m/09cds",alias:null},
  {name:"Asphyxia",entity:"/m/0p7w5",alias:null},
  {name:"Asterixis",entity:"/m/077dxt",alias:null},
  {name:"Asthma",entity:"/m/0c78m",alias:null},
  {name:"Astigmatism",entity:"/m/0chf1d",alias:null},
  {name:"Ataxia",entity:"/m/0l95",alias:null},
  {name:"Athetosis",entity:"/m/03hrw8",alias:null},
  {name:"Atony",entity:"/m/08bp0k",alias:null},
  {name:"Atopic dermatitis",entity:"/m/06xb9t",alias:null},
  {name:"Atrophy",entity:"/m/034y_l",alias:null},
  {name:"Attention deficit hyperactivity disorder",entity:"/m/0h99n",alias:null},
  {name:"Auditory hallucination",entity:"/m/03hfxpg",alias:null},
  {name:"Aura",entity:"/m/07ms80",alias:null},
  {name:"Autism",entity:"/m/0gwj",alias:null},
  {name:"Autoimmune disease",entity:"/m/04dx3qn",alias:null},
  {name:"Autoimmune hemolytic anemia",entity:"/m/0b1p89",alias:null},
  {name:"AV nodal reentrant tachycardia",entity:"/m/03rsgd",alias:null},
  {name:"Avoidant personality disorder",entity:"/m/01_4_n",alias:null},
  {name:"Avolition",entity:"/m/01sbgb",alias:null},
  {name:"Azotemia",entity:"/m/0dn4_",alias:null},
  {name:"Back pain",entity:"/m/0142ky",alias:null},
  {name:"Bacterial arthritis",entity:"/m/02nrsk",alias:null},
  {name:"Bacterial vaginosis",entity:"/m/01glh",alias:null},
  {name:"Bad breath",entity:"/m/025hzf",alias:null},
  {name:"Balance disorder",entity:"/m/0180jb",alias:null},
  {name:"Behçet's disease",entity:"/m/025t67z",alias:null},
  {name:"Bell's palsy",entity:"/m/0dxdd",alias:null},
  {name:"Bigeminy",entity:"/m/099t0f",alias:null},
  {name:"Biliary colic",entity:"/m/026stnc",alias:null},
  {name:"Biliary dyskinesia",entity:"/m/04cy_nk",alias:null},
  {name:"Binge eating",entity:"/m/01t96l",alias:null},
  {name:"Bipolar disorder",entity:"/m/01g2q",alias:null},
  {name:"Birthmark",entity:"/m/01ljf2",alias:null},
  {name:"Black eye",entity:"/m/065wv1",alias:null},
  {name:"Blackout",entity:"/m/02pnflk",alias:null},
  {name:"Bladder cancer",entity:"/m/01bcp7",alias:null},
  {name:"Bleeding",entity:"/m/012n6x",alias:null},
  {name:"Bleeding diathesis",entity:"/m/037mv0",alias:null},
  {name:"Bleeding on probing",entity:"/m/02rtqbt",alias:null},
  {name:"Blepharospasm",entity:"/m/08k14_",alias:null},
  {name:"Blindness",entity:"/m/064kj9p",alias:null},
  {name:"Blister",entity:"/m/01k1jq",alias:null},
  {name:"Bloating",entity:"/m/011dzgb6",alias:null},
  {name:"Blood blister",entity:"/m/05zy6c",alias:null},
  {name:"Blood in stool",entity:"/m/08cmfm",alias:null},
  {name:"Bloody show",entity:"/m/05q5s6",alias:null},
  {name:"Blurred vision",entity:"/m/03g_gxj",alias:null},
  {name:"Blushing",entity:"/m/01jyxg",alias:null},
  {name:"Body odor",entity:"/m/037ywk",alias:null},
  {name:"Boil",entity:"/m/03xp5n",alias:null},
  {name:"Bone fracture",entity:"/m/03fz1q",alias:null},
  {name:"Bone tumor",entity:"/m/01t125",alias:null},
  {name:"Borderline personality disorder",entity:"/m/0134rc",alias:null},
  {name:"Bowel infarction",entity:"/m/02r0rdw",alias:null},
  {name:"Bowel obstruction",entity:"/m/01vzqb",alias:null},
  {name:"Brachycephaly",entity:"/m/01hrdy",alias:null},
  {name:"Bradycardia",entity:"/m/01r__",alias:null},
  {name:"Brain damage",entity:"/m/01sbk1",alias:null},
  {name:"Brain death",entity:"/m/019m0c",alias:null},
  {name:"Braxton Hicks contractions",entity:"/m/03_81f",alias:null},
  {name:"Breakthrough bleeding",entity:"/m/04fjyf",alias:null},
  {name:"Breast cancer",entity:"/m/0j8hd",alias:null},
  {name:"Breast hypertrophy",entity:"/m/025t7qd",alias:null},
  {name:"Breast lump",entity:"/m/080fvq7",alias:null},
  {name:"Breast pain",entity:"/m/06pp7p",alias:null},
  {name:"Bronchiectasis",entity:"/m/01w_2w",alias:null},
  {name:"Bronchitis",entity:"/m/047gmsk",alias:null},
  {name:"Bronchospasm",entity:"/m/02_5n7",alias:null},
  {name:"Brown-Séquard's ",entity:"/m/03vwc5",alias:null},
  {name:"Brucellosis",entity:"/m/0270q1",alias:null},
  {name:"Bruise",entity:"/m/02zpsl",alias:null},
  {name:"Bruit",entity:"/m/07qwnz",alias:null},
  {name:"Bruxism",entity:"/m/0149nm",alias:null},
  {name:"Bubo",entity:"/m/02777pt",alias:null},
  {name:"Bulbar palsy",entity:"/m/02qb7yy",alias:null},
  {name:"Bullying",entity:"/m/027vd9",alias:null},
  {name:"Bunion",entity:"/m/01l2ky",alias:null},
  {name:"Burn",entity:"/m/01hwqk",alias:null},
  {name:"Burning mouth syndrome",entity:"/m/03_3c6",alias:null},
  {name:"Bursitis",entity:"/m/034z18",alias:null},
  {name:"Cachexia",entity:"/m/01wxhm",alias:null},
  {name:"Calcaneal spur",entity:"/m/025t1sl",alias:null},
  {name:"Callus",entity:"/m/01l2l9",alias:null},
  {name:"Cancer",entity:"/m/0qcr0",alias:null},
  {name:"Candidiasis",entity:"/m/020gv",alias:null},
  {name:"Canker sore",entity:"/m/05frfm",alias:null},
  {name:"Cardiac arrest",entity:"/m/0gg4h",alias:null},
  {name:"Cardiac arrhythmia",entity:"/m/01pf6",alias:null},
  {name:"Cardiomegaly",entity:"/m/08_51g",alias:null},
  {name:"Cardiovascular disease",entity:"/m/02k6hp",alias:null},
  {name:"Carpal tunnel syndrome",entity:"/m/0fl_v",alias:null},
  {name:"Cataplexy",entity:"/m/07f_8c",alias:null},
  {name:"Cataract",entity:"/m/0m7h6",alias:null},
  {name:"Catatonia",entity:"/m/01lxx",alias:null},
  {name:"Cauda equina syndrome",entity:"/m/04yb5z",alias:null},
  {name:"Celiac disease",entity:"/m/0h1pq",alias:null},
  {name:"Cerebellar ataxia",entity:"/m/02vkcrn",alias:null},
  {name:"Cerebral edema",entity:"/m/0219bz",alias:null},
  {name:"Cervical cancer",entity:"/m/0d_bk",alias:null},
  {name:"Cervicitis",entity:"/m/020v3l",alias:null},
  {name:"Chagas disease",entity:"/m/0208m",alias:null},
  {name:"Chalazion",entity:"/m/03gf8g",alias:null},
  {name:"Chancre",entity:"/m/01ny_v",alias:null},
  {name:"Cheilitis",entity:"/m/0gj51x",alias:null},
  {name:"Chemosis",entity:"/m/04jr5f",alias:null},
  {name:"Chest pain",entity:"/m/02np4v",alias:null},
  {name:"Cheyne-Stokes respiration",entity:"/m/036k30",alias:null},
  {name:"Chickenpox",entity:"/m/01r6j",alias:null},
  {name:"Chikungunya virus infection",entity:"/m/01__7l",alias:"Chikungunya"},
  {name:"Chills",entity:"/m/02mdc7",alias:null},
  {name:"Choking",entity:"/m/0168pw",alias:null},
  {name:"Cholera",entity:"/m/024c2",alias:null},
  {name:"Cholestasis",entity:"/m/07t2pp",alias:null},
  {name:"Chorea",entity:"/m/03d70n",alias:null},
  {name:"Chronic Obstructive Pulmonary Disease",entity:"/m/0gzv0",alias:null},
  {name:"Chronic pain",entity:"/m/012clh",alias:null},
  {name:"Chronic prostatitis/chronic pelvic pain syndrome",entity:"/m/043jxv5",alias:null},
  {name:"Cirrhosis",entity:"/m/097ns",alias:null},
  {name:"Claudication",entity:"/m/05c1gt",alias:null},
  {name:"Cleft lip and cleft palate",entity:"/m/07y4w6s",alias:null},
  {name:"Clitoromegaly",entity:"/m/04jpnx",alias:null},
  {name:"Clonus",entity:"/m/02zdnj",alias:null},
  {name:"Clostridium difficile infection",entity:"/m/02cxr0",alias:null},
  {name:"Coagulopathy",entity:"/m/065b00",alias:null},
  {name:"Coccydynia",entity:"/m/031c9y",alias:null},
  {name:"Coffee ground vomiting",entity:"/m/02n2zp",alias:null},
  {name:"Cognitive deficit",entity:"/m/02py0vt",alias:null},
  {name:"Colitis",entity:"/m/043hy3",alias:null},
  {name:"Collapse",entity:"/m/026gdg4",alias:null},
  {name:"Color blindness",entity:"/m/022xh",alias:null},
  {name:"Coma",entity:"/m/01qw1",alias:null},
  {name:"Comedo",entity:"/m/02ry9q",alias:null},
  {name:"Common cold",entity:"/m/0n073",alias:"Cold"},
  {name:"Compartment syndrome",entity:"/m/01j0hs",alias:null},
  {name:"Compulsive behavior",entity:"/m/0281lfw",alias:null},
  {name:"Compulsive hoarding",entity:"/m/0240_y",alias:null},
  {name:"Concussion",entity:"/m/023ndx",alias:null},
  {name:"Conductive hearing loss",entity:"/m/04fmtx",alias:null},
  {name:"Confabulation",entity:"/m/0371d4",alias:null},
  {name:"Congenital heart defect",entity:"/m/03k22s",alias:null},
  {name:"Conjunctivitis",entity:"/m/0c36_",alias:"Pink eye"},
  {name:"Constipation",entity:"/m/016kf9",alias:null},
  {name:"Contracture",entity:"/m/04f49cb",alias:null},
  {name:"Convulsion",entity:"/m/04lcpr5",alias:null},
  {name:"Coprolalia",entity:"/m/02gp9x",alias:null},
  {name:"Corneal abrasion",entity:"/m/07ldcz",alias:null},
  {name:"Coryza",entity:"/m/0c532h",alias:"Stuffy nose"},
  {name:"Cough",entity:"/m/01b_21",alias:null},
  {name:"Crackles",entity:"/m/023rn8",alias:null},
  {name:"Cramp",entity:"/m/024_yy",alias:null},
  {name:"Crepitus",entity:"/m/05bws4",alias:null},
  {name:"Crohn's disease",entity:"/m/0h1n9",alias:null},
  {name:"Cryptorchidism",entity:"/m/025nm6",alias:null},
  {name:"Cushing's syndrome",entity:"/m/0mzm2",alias:null},
  {name:"Cutaneous condition",entity:"/m/08cqsh",alias:null},
  {name:"Cyanosis",entity:"/m/021fq9",alias:null},
  {name:"Cyst",entity:"/m/019rnl",alias:null},
  {name:"Cysticercosis",entity:"/m/0394df",alias:null},
  {name:"Dandruff",entity:"/m/022y19",alias:null},
  {name:"Death rattle",entity:"/m/0660m0",alias:null},
  {name:"Deep vein thrombosis",entity:"/m/02r3jk",alias:null},
  {name:"Deformity",entity:"/m/0383j_",alias:null},
  {name:"Dehydration",entity:"/m/014961",alias:null},
  {name:"Delayed onset muscle soreness",entity:"/m/03dcyh",alias:null},
  {name:"Delirium",entity:"/m/014qfd",alias:null},
  {name:"Delirium tremens",entity:"/m/0fpnjr",alias:null},
  {name:"Delusional disorder",entity:"/m/01l7xz",alias:null},
  {name:"Dementia",entity:"/m/09klv",alias:null},
  {name:"Dengue fever",entity:"/m/09wsg",alias:null},
  {name:"Dengue virus",entity:"/m/0g58pft",alias:null},
  {name:"Dental plaque",entity:"/m/073t8x",alias:null},
  {name:"Dentin hypersensitivity",entity:"/m/0d7gj3",alias:null},
  {name:"Dependent personality disorder",entity:"/m/01sydv",alias:null},
  {name:"Depersonalization",entity:"/m/01zn1_",alias:null},
  {name:"Depigmentation",entity:"/m/027cv8v",alias:null},
  {name:"Depression",entity:"/m/03f_cb",alias:null},
  {name:"Derealization",entity:"/m/02wv6r8",alias:null},
  {name:"Dermatitis",entity:"/m/06x09g",alias:null},
  {name:"Dermatographic urticaria",entity:"/m/06djbj",alias:null},
  {name:"Desquamation",entity:"/m/05pbx5",alias:null},
  {name:"Developmental disability",entity:"/m/06xd3t",alias:null},
  {name:"Diabetes insipidus",entity:"/m/0c5s4",alias:null},
  {name:"Diabetes mellitus",entity:"/m/0c58k",alias:"Diabetes"},
  {name:"Diaphoresis",entity:"/m/01q1s3",alias:null},
  {name:"Diarrhea",entity:"/m/0f3kl",alias:null},
  {name:"Diastolic heart failure",entity:"/m/02pv6ym",alias:null},
  {name:"Diathesis",entity:"/m/0sghsdb",alias:null},
  {name:"Diplopia",entity:"/m/03x17h",alias:null},
  {name:"Disseminated intravascular coagulation",entity:"/m/01jjrv",alias:null},
  {name:"Dissociation",entity:"/m/02l_0n",alias:null},
  {name:"Dissociative disorder",entity:"/m/07bc25",alias:null},
  {name:"Dizziness",entity:"/m/033mg5",alias:null},
  {name:"Down's syndrome",entity:"/m/029s1",alias:null},
  {name:"Drooling",entity:"/m/019bfk",alias:null},
  {name:"Dry eye syndrome",entity:"/m/03ckn0",alias:null},
  {name:"Dryness",entity:"/m/0g9_00t",alias:null},
  {name:"Dupuytren's contracture",entity:"/m/036l18",alias:null},
  {name:"Dwarfism",entity:"/m/010vmq",alias:null},
  {name:"Dysarthria",entity:"/m/03ygz2",alias:null},
  {name:"Dysautonomia",entity:"/m/02510j",alias:null},
  {name:"Dysentery",entity:"/m/0h3bn",alias:null},
  {name:"Dysesthesia",entity:"/m/0264gx3",alias:null},
  {name:"Dysfunctional uterine bleeding",entity:"/m/04cslz",alias:null},
  {name:"Dysgeusia",entity:"/m/01d3gn",alias:null},
  {name:"Dyskinesia",entity:"/m/03_xjz",alias:null},
  {name:"Dysmenorrhea",entity:"/m/0255t_",alias:null},
  {name:"Dyspareunia",entity:"/m/01qqq7",alias:null},
  {name:"Dysphagia",entity:"/m/01bztl",alias:null},
  {name:"Dysphonia",entity:"/m/07_7w6",alias:null},
  {name:"Dysphoria",entity:"/m/055f85",alias:null},
  {name:"Dystonia",entity:"/m/02_x8m",alias:null},
  {name:"Dysuria",entity:"/m/03wblc",alias:null},
  {name:"Ear pain",entity:"/m/05vywy",alias:null},
  {name:"EBOV",entity:"/m/0117wrtj",alias:"Ebola"},
  {name:"Ecchymosis",entity:"/m/05b6rk9",alias:null},
  {name:"Echolalia",entity:"/m/03y0cn",alias:null},
  {name:"Edema",entity:"/m/0j80c",alias:null},
  {name:"Electrolyte imbalance",entity:"/m/03nkmb",alias:null},
  {name:"Elevated alkaline phosphatase",entity:"/m/063ykc9",alias:null},
  {name:"Emaciation",entity:"/m/070kyz",alias:null},
  {name:"Emotional detachment",entity:"/m/092b1g",alias:null},
  {name:"Emotional dysregulation",entity:"/m/0b3n_k",alias:null},
  {name:"Encephalitis",entity:"/m/09c_t",alias:null},
  {name:"Encephalopathy",entity:"/m/022tc0",alias:null},
  {name:"Encopresis",entity:"/m/0298jv",alias:null},
  {name:"Endometrial cancer",entity:"/m/0259rv",alias:null},
  {name:"Endometrial hyperplasia",entity:"/m/02rc7qj",alias:null},
  {name:"Endometriosis",entity:"/m/0d_9n",alias:null},
  {name:"Endometriosis of ovary",entity:"/m/05q45f7",alias:null},
  {name:"Enlarged uterus",entity:"/m/075k1p8",alias:null},
  {name:"Enterocolitis",entity:"/m/07y4wgq",alias:null},
  {name:"Enthesitis",entity:"/m/0gs1mr",alias:null},
  {name:"Enthesopathy",entity:"/m/08bvg8",alias:null},
  {name:"Enuresis",entity:"/m/03gq2nq",alias:null},
  {name:"Eosinophilia",entity:"/m/01jmy5",alias:null},
  {name:"Epicanthic fold",entity:"/m/014x2z",alias:null},
  {name:"Epidermoid cyst",entity:"/m/04mw9m",alias:null},
  {name:"Epilepsy",entity:"/m/02vrr",alias:null},
  {name:"Epileptic seizure",entity:"/m/06rhk",alias:null},
  {name:"Epiphora",entity:"/m/02r3mv3",alias:null},
  {name:"Erectile dysfunction",entity:"/m/03tkm",alias:null},
  {name:"Eructation",entity:"/m/03q5_w",alias:null},
  {name:"Erythema",entity:"/m/02mcv2",alias:null},
  {name:"Erythema chronicum migrans",entity:"/m/0bzv6k",alias:null},
  {name:"Erythema multiforme",entity:"/m/03s352",alias:null},
  {name:"Erythema nodosum",entity:"/m/08fm2f",alias:null},
  {name:"Eschar",entity:"/m/03_m2p",alias:null},
  {name:"Esophageal varices",entity:"/m/0340vp",alias:null},
  {name:"Esophagitis",entity:"/m/01b_b2",alias:null},
  {name:"Esotropia",entity:"/m/0184pc",alias:null},
  {name:"Euphoria",entity:"/m/02rj8by",alias:null},
  {name:"Exanthem",entity:"/m/07bblt",alias:null},
  {name:"Excessive daytime sleepiness",entity:"/m/02y_82q",alias:null},
  {name:"Exophthalmos",entity:"/m/05mjhy",alias:null},
  {name:"Exotropia",entity:"/m/099x_8",alias:null},
  {name:"Extrapyramidal symptoms",entity:"/m/09gkmws",alias:null},
  {name:"Exudate",entity:"/m/02yj5k",alias:null},
  {name:"Eye pain",entity:"/m/05fs77x",alias:null},
  {name:"Eye strain",entity:"/m/07v7rh",alias:null},
  {name:"Facial nerve paralysis",entity:"/m/04mpk9",alias:null},
  {name:"Far-sightedness",entity:"/m/0248jp",alias:null},
  {name:"Fasciculation",entity:"/m/062phb",alias:null},
  {name:"Fatigue",entity:"/m/01j6t0",alias:null},
  {name:"Fatty liver",entity:"/m/03s7fs",alias:null},
  {name:"Febrile neutrophilic dermatosis",entity:"/m/09jw9n",alias:null},
  {name:"Febrile seizure",entity:"/m/013q86",alias:null},
  {name:"Fecal incontinence",entity:"/m/018h28",alias:null},
  {name:"Female infertility",entity:"/m/03bx9gs",alias:null},
  {name:"Fetal distress",entity:"/m/02sj16",alias:null},
  {name:"Fever",entity:"/m/0cjf0",alias:null},
  {name:"Fibrillation",entity:"/m/0118lbwm",alias:null},
  {name:"Fibromyalgia",entity:"/m/01v3ks",alias:null},
  {name:"Fibrosis",entity:"/m/03nq4p",alias:null},
  {name:"Fidgeting",entity:"/m/04y6tl1",alias:null},
  {name:"Flaccid paralysis",entity:"/m/02qkp38",alias:null},
  {name:"Flatulence",entity:"/m/06vg9d",alias:null},
  {name:"Floater",entity:"/m/018j1l",alias:null},
  {name:"Flushing",entity:"/m/028n_3",alias:null},
  {name:"Folate deficiency",entity:"/m/0dt6ml",alias:null},
  {name:"Folie à deux",entity:"/m/03281",alias:null},
  {name:"Food addiction",entity:"/m/04sws8",alias:null},
  {name:"Food poisoning",entity:"/m/02m76d",alias:null},
  {name:"Foot drop",entity:"/m/0bcwy3",alias:null},
  {name:"Formication",entity:"/m/02p4g5n",alias:null},
  {name:"Freckle",entity:"/m/0fyd3",alias:null},
  {name:"Frequent urination",entity:"/m/0c3_wg5",alias:null},
  {name:"Frostbite",entity:"/m/0213yl",alias:null},
  {name:"Fuchs' dystrophy",entity:"/m/05pb2q",alias:null},
  {name:"Fugue state",entity:"/m/02ybr",alias:null},
  {name:"Gait abnormality",entity:"/m/06h94m",alias:null},
  {name:"Galactorrhea",entity:"/m/03xmsb",alias:null},
  {name:"Gallstone",entity:"/m/01q6mh",alias:null},
  {name:"Gangrene",entity:"/m/01jj75",alias:null},
  {name:"Gastritis",entity:"/m/03y91v",alias:null},
  {name:"Gastroesophageal reflux disease",entity:"/m/01b_5g",alias:"Acid reflux"},
  {name:"Gastrointestinal bleeding",entity:"/m/03njtl",alias:null},
  {name:"Gastroparesis",entity:"/m/02w1n2",alias:null},
  {name:"Generalised tonic-clonic seizure",entity:"/m/02r6d3v",alias:null},
  {name:"Generalized anxiety disorder",entity:"/m/02zr3h",alias:null},
  {name:"Genital herpes",entity:"/m/05m_zpz",alias:null},
  {name:"Genital wart",entity:"/m/019thv",alias:null},
  {name:"Genu varum",entity:"/m/03pk5z",alias:null},
  {name:"Giant-cell arteritis",entity:"/m/07s7n",alias:null},
  {name:"Gigantism",entity:"/m/01jmvq",alias:null},
  {name:"Gingival recession",entity:"/m/0dr8s9",alias:null},
  {name:"Gingivitis",entity:"/m/01d20w",alias:null},
  {name:"Glabrousness",entity:"/m/05__9r",alias:null},
  {name:"Gliosis",entity:"/m/0chqj1",alias:null},
  {name:"Globus pharyngis",entity:"/m/0czdw5",alias:null},
  {name:"Glomerulonephritis",entity:"/m/04gfv_",alias:null},
  {name:"Glossitis",entity:"/m/07ckc_",alias:null},
  {name:"Glucose-6-phosphate dehydrogenase deficiency",entity:"/m/021tw2",alias:null},
  {name:"Glycosuria",entity:"/m/05pcqg",alias:null},
  {name:"Goitre",entity:"/m/036zm",alias:null},
  {name:"Gonorrhea",entity:"/m/0mh4s",alias:null},
  {name:"Goose bumps",entity:"/m/03ck2w",alias:null},
  {name:"Gout",entity:"/m/0ffxt",alias:null},
  {name:"Grandiosity",entity:"/m/041cwm",alias:null},
  {name:"Granuloma",entity:"/m/029fv3",alias:null},
  {name:"Granuloma annulare",entity:"/m/0cvpr9",alias:null},
  {name:"Graves' ophthalmopathy",entity:"/m/0fl3qm",alias:null},
  {name:"Greasy hair",entity:"/m/0nbv1vz",alias:null},
  {name:"Ground-glass opacity",entity:"/m/0j26_bj",alias:null},
  {name:"Growth hormone deficiency",entity:"/m/02xh6k",alias:null},
  {name:"Guttate psoriasis",entity:"/m/05c3rty",alias:null},
  {name:"Gynecomastia",entity:"/m/07cszr",alias:null},
  {name:"Haemophilia",entity:"/m/03myr",alias:null},
  {name:"Hair loss",entity:"/m/03bwzh1",alias:null},
  {name:"Hallucination",entity:"/m/0d3gy",alias:null},
  {name:"Hammer toe",entity:"/m/03vwp3",alias:null},
  {name:"Headache",entity:"/m/0j5fv",alias:null},
  {name:"Hearing loss",entity:"/m/014wq_",alias:null},
  {name:"Heart block",entity:"/m/031q2c",alias:null},
  {name:"Heart failure",entity:"/m/01l2m3",alias:null},
  {name:"Heart murmur",entity:"/m/01jg1z",alias:null},
  {name:"Heartburn",entity:"/m/01bfsv",alias:null},
  {name:"Heat intolerance",entity:"/m/0rpj80_",alias:null},
  {name:"Heavy legs",entity:"/m/051ynwt",alias:null},
  {name:"Heberden's node",entity:"/m/054s8y",alias:null},
  {name:"Hemangioma",entity:"/m/03jcdy",alias:null},
  {name:"Hematemesis",entity:"/m/02n2t1",alias:null},
  {name:"Hematochezia",entity:"/m/02n2gk",alias:null},
  {name:"Hematoma",entity:"/m/032ssz",alias:null},
  {name:"Hematospermia",entity:"/m/0bblkc",alias:null},
  {name:"Hematuria",entity:"/m/02sc7d",alias:null},
  {name:"Hemiparesis",entity:"/m/03j3s",alias:null},
  {name:"Hemiplegia",entity:"/m/04n8p1",alias:null},
  {name:"Hemispatial neglect",entity:"/m/03ttjj",alias:null},
  {name:"Hemolysis",entity:"/m/0j8q4",alias:null},
  {name:"Hemolytic anemia",entity:"/m/02skgx",alias:null},
  {name:"Hemoptysis",entity:"/m/01g920",alias:null},
  {name:"Hemorrhoids",entity:"/m/017f7c",alias:null},
  {name:"Hemothorax",entity:"/m/06rt3n",alias:null},
  {name:"Hepatic encephalopathy",entity:"/m/046cxb",alias:null},
  {name:"Hepatitis",entity:"/m/09jg8",alias:null},
  {name:"Hepatomegaly",entity:"/m/055_gj",alias:null},
  {name:"Hepatorenal syndrome",entity:"/m/06vqzq",alias:null},
  {name:"Hepatosplenomegaly",entity:"/m/03zr21",alias:null},
  {name:"Hepatotoxicity",entity:"/m/02clhl",alias:null},
  {name:"Herpes simplex",entity:"/m/0gxbfm",alias:null},
  {name:"Heterochromia",entity:"/m/02w_rc",alias:null},
  {name:"Hiccup",entity:"/m/02p3nc",alias:null},
  {name:"Hickey",entity:"/m/02497k",alias:null},
  {name:"High Blood Pressure",entity:"/m/0k95h",alias:null},
  {name:"Hirsutism",entity:"/m/0ps0b",alias:null},
  {name:"Histoplasmosis",entity:"/m/022tb8",alias:null},
  {name:"HIV/AIDS",entity:"/m/0d19y2",alias:null},
  {name:"Hives",entity:"/m/03nky3",alias:null},
  {name:"Homans sign",entity:"/m/08ytrd",alias:null},
  {name:"Horner's syndrome",entity:"/m/04v0fj",alias:null},
  {name:"Hostility",entity:"/m/02p74_2",alias:null},
  {name:"Hot flash",entity:"/m/033488",alias:null},
  {name:"Hydrocele",entity:"/m/04vy02",alias:null},
  {name:"Hydrocephalus",entity:"/m/01cw5r",alias:null},
  {name:"Hyperactivity",entity:"/m/04txf7",alias:null},
  {name:"Hyperacusis",entity:"/m/04xpzs",alias:null},
  {name:"Hyperaemia",entity:"/m/08859_",alias:null},
  {name:"Hyperalgesia",entity:"/m/03z_m7",alias:null},
  {name:"Hypercalcaemia",entity:"/m/02k540",alias:null},
  {name:"Hypercapnia",entity:"/m/02hlph",alias:null},
  {name:"Hypercholesterolemia",entity:"/m/02k7pj",alias:null},
  {name:"Hyperemesis gravidarum",entity:"/m/06t7dc",alias:null},
  {name:"Hyperesthesia",entity:"/m/0btccj",alias:null},
  {name:"Hyperglycemia",entity:"/m/0kfqw",alias:null},
  {name:"Hyperhidrosis",entity:"/m/03jbly",alias:null},
  {name:"Hyperkalemia",entity:"/m/037h0g",alias:null},
  {name:"Hyperkeratosis",entity:"/m/05qymp",alias:null},
  {name:"Hyperlipidemia",entity:"/m/05f45h",alias:null},
  {name:"Hypermobility",entity:"/m/0b9f_5",alias:null},
  {name:"Hypernatremia",entity:"/m/03xr5j",alias:null},
  {name:"Hyperpigmentation",entity:"/m/046z7d",alias:null},
  {name:"Hyperreflexia",entity:"/m/04bl90",alias:null},
  {name:"Hypersalivation",entity:"/m/0fpjgc1",alias:null},
  {name:"Hypersexuality",entity:"/m/01g5ln",alias:null},
  {name:"Hypersomnia",entity:"/m/03cfcn",alias:null},
  {name:"Hypertelorism",entity:"/m/08wwvw",alias:null},
  {name:"Hyperthermia",entity:"/m/0k10t",alias:null},
  {name:"Hyperthyroidism",entity:"/m/03hz0",alias:null},
  {name:"Hypertonia",entity:"/m/092xnv",alias:null},
  {name:"Hypertrichosis",entity:"/m/04lj5j",alias:null},
  {name:"Hypertriglyceridemia",entity:"/m/02_sbz",alias:null},
  {name:"Hypertrophy",entity:"/m/02vrdn",alias:null},
  {name:"Hyperuricemia",entity:"/m/02hl8g",alias:null},
  {name:"Hyperventilation",entity:"/m/021m_f",alias:null},
  {name:"Hyphema",entity:"/m/08dkq0",alias:null},
  {name:"Hypoactive sexual desire disorder",entity:"/m/0255l5",alias:null},
  {name:"Hypoalbuminemia",entity:"/m/09bl05",alias:null},
  {name:"Hypocalcaemia",entity:"/m/02k53m",alias:null},
  {name:"Hypoesthesia",entity:"/m/027q6ds",alias:null},
  {name:"Hypoglycemia",entity:"/m/03gwt",alias:null},
  {name:"Hypogonadism",entity:"/m/038k4x",alias:null},
  {name:"Hypohidrosis",entity:"/m/04yfs7",alias:null},
  {name:"Hypokalemia",entity:"/m/03vmt0",alias:null},
  {name:"Hypokinesia",entity:"/m/06_8j3",alias:null},
  {name:"Hypomania",entity:"/m/0bk6q",alias:null},
  {name:"Hypomenorrhea",entity:"/m/0412nq4",alias:null},
  {name:"Hypoparathyroidism",entity:"/m/0340yl",alias:null},
  {name:"Hypopigmentation",entity:"/m/048hpn",alias:null},
  {name:"Hypotension",entity:"/m/02hvph",alias:null},
  {name:"Hypothermia",entity:"/m/012rps",alias:null},
  {name:"Hypothyroidism",entity:"/m/0hg11",alias:null},
  {name:"Hypotonia",entity:"/m/03wbww",alias:null},
  {name:"Hypoventilation",entity:"/m/02fwvl",alias:null},
  {name:"Hypovolemia",entity:"/m/02hwb2",alias:null},
  {name:"Hypoxemia",entity:"/m/025sd3c",alias:null},
  {name:"Hypoxia",entity:"/m/03gns",alias:null},
  {name:"Ichthyosis",entity:"/m/02wgfv",alias:null},
  {name:"Ileus",entity:"/m/0443mq",alias:null},
  {name:"Immunodeficiency",entity:"/m/02yg4w",alias:null},
  {name:"Immunosuppression",entity:"/m/016mlj",alias:null},
  {name:"Impetigo",entity:"/m/0mzty",alias:null},
  {name:"Implantation bleeding",entity:"/m/013027b9",alias:null},
  {name:"Indigestion",entity:"/m/04kl78",alias:null},
  {name:"Infarction",entity:"/m/02vnfx",alias:null},
  {name:"Infection",entity:"/m/098s1",alias:null},
  {name:"Infectious mononucleosis",entity:"/m/0qjk8",alias:"Mononucleosis"},
  {name:"Inferiority complex",entity:"/m/03c9vn",alias:null},
  {name:"Infertility",entity:"/m/018g78",alias:null},
  {name:"Inflammation",entity:"/m/0j7_w",alias:null},
  {name:"Inflammatory bowel disease",entity:"/m/02x0yg",alias:null},
  {name:"Influenza",entity:"/m/0cycc",alias:null},
  {name:"Ingrown hair",entity:"/m/0cmmcy",alias:null},
  {name:"Insomnia",entity:"/m/0ddwt",alias:null},
  {name:"Intellectual disability",entity:"/m/09fz4",alias:null},
  {name:"Intermittent claudication",entity:"/m/04qydt",alias:null},
  {name:"Internal bleeding",entity:"/m/02xb32",alias:null},
  {name:"Intertrigo",entity:"/m/05l4gz",alias:null},
  {name:"Intracerebral hemorrhage",entity:"/m/08g5q7",alias:null},
  {name:"Intracranial aneurysm",entity:"/m/01g45j",alias:null},
  {name:"Intrauterine growth restriction",entity:"/m/05pdffb",alias:null},
  {name:"Inverted nipple",entity:"/m/071nxk",alias:null},
  {name:"Iron deficiency",entity:"/m/014x04",alias:null},
  {name:"Iron overload",entity:"/m/02n_ct",alias:null},
  {name:"Irregular menstruation",entity:"/m/05bm66n",alias:null},
  {name:"Irritability",entity:"/m/083h_x",alias:null},
  {name:"Irritant diaper dermatitis",entity:"/m/025r6w",alias:null},
  {name:"Ischemia",entity:"/m/02gr6s",alias:null},
  {name:"Itch",entity:"/m/04kllm9",alias:null},
  {name:"Jaundice",entity:"/m/0hgxh",alias:null},
  {name:"Joint effusion",entity:"/m/0b74b60",alias:null},
  {name:"Joint pain",entity:"/m/021hck",alias:null},
  {name:"Joint stiffness",entity:"/m/088b11",alias:null},
  {name:"Jugular venous pressure",entity:"/m/03f3w1",alias:null},
  {name:"Kaposi's sarcoma",entity:"/m/0bqpg",alias:null},
  {name:"Kawasaki disease",entity:"/m/040k6g",alias:null},
  {name:"Keratitis",entity:"/m/02dfr6",alias:null},
  {name:"Ketoacidosis",entity:"/m/02mwg6",alias:null},
  {name:"Ketonuria",entity:"/m/095xr2",alias:null},
  {name:"Kidney failure",entity:"/m/01psyx",alias:null},
  {name:"Kidney stone",entity:"/m/09hbx",alias:null},
  {name:"Knee effusion",entity:"/m/03bxmbn",alias:null},
  {name:"Knee pain",entity:"/m/09v868h",alias:null},
  {name:"Koilonychia",entity:"/m/0gj4qx",alias:null},
  {name:"Kussmaul breathing",entity:"/m/036mkm",alias:null},
  {name:"Kyphosis",entity:"/m/02jrl1",alias:null},
  {name:"Labored breathing",entity:"/m/09k6f04",alias:null},
  {name:"Labyrinthitis",entity:"/m/03m31g",alias:null},
  {name:"Lactose intolerance",entity:"/m/0fp3b",alias:null},
  {name:"Lanugo",entity:"/m/04g22n",alias:null},
  {name:"Laryngitis",entity:"/m/02l37c",alias:null},
  {name:"Laryngopharyngeal reflux",entity:"/m/047bx2y",alias:null},
  {name:"Laryngospasm",entity:"/m/08zhxx",alias:null},
  {name:"Learning disability",entity:"/m/02qwpq0",alias:null},
  {name:"Left Bundle Branch Block",entity:"/m/09k76g",alias:null},
  {name:"Left ventricular hypertrophy",entity:"/m/04dxph",alias:null},
  {name:"Leishmaniasis",entity:"/m/01c5s1",alias:null},
  {name:"Leprosy",entity:"/m/0c5f7",alias:null},
  {name:"Leptospirosis",entity:"/m/02_j9l",alias:null},
  {name:"Lethargy",entity:"/m/012815pn",alias:null},
  {name:"Leukemia",entity:"/m/04psf",alias:null},
  {name:"Leukocytosis",entity:"/m/03btw1",alias:null},
  {name:"Leukopenia",entity:"/m/03zrfj",alias:null},
  {name:"Leukoplakia",entity:"/m/03l365",alias:null},
  {name:"Leukorrhea",entity:"/m/06kjt9",alias:null},
  {name:"Lhermitte's sign",entity:"/m/064n9x",alias:null},
  {name:"Lightheadedness",entity:"/m/079p0q",alias:null},
  {name:"Limp",entity:"/m/04plrq",alias:null},
  {name:"Lipodystrophy",entity:"/m/01l2st",alias:null},
  {name:"Livedo reticularis",entity:"/m/08wrk9",alias:null},
  {name:"Liver failure",entity:"/m/02psvcf",alias:null},
  {name:"Locked-in syndrome",entity:"/m/014mtn",alias:null},
  {name:"Logorrhea",entity:"/m/09v4pxz",alias:null},
  {name:"Lordosis",entity:"/m/03_039",alias:null},
  {name:"Low back pain",entity:"/m/020hwm",alias:null},
  {name:"Low birth weight",entity:"/m/0dl9s49",alias:null},
  {name:"Lower respiratory tract infection",entity:"/m/03txkl",alias:null},
  {name:"Lung cancer",entity:"/m/04p3w",alias:null},
  {name:"Lupus nephritis",entity:"/m/05fq5c",alias:null},
  {name:"Lyme disease",entity:"/m/01kcry",alias:null},
  {name:"Lymphedema",entity:"/m/04r36",alias:null},
  {name:"Lymphocytopenia",entity:"/m/08z6j9",alias:null},
  {name:"Lymphocytosis",entity:"/m/01jn3l",alias:null},
  {name:"Macrocephaly",entity:"/m/07b8s3",alias:null},
  {name:"Maculopapular rash",entity:"/m/05lrqf",alias:null},
  {name:"Major depressive disorder",entity:"/m/02bft",alias:null},
  {name:"Malabsorption",entity:"/m/03f07j",alias:null},
  {name:"Malaise",entity:"/m/0418s3",alias:null},
  {name:"Malar rash",entity:"/m/04t_81",alias:null},
  {name:"Malaria",entity:"/m/0542n",alias:null},
  {name:"Male infertility",entity:"/m/03bx917",alias:null},
  {name:"Malnutrition",entity:"/m/01m4w4",alias:null},
  {name:"Malocclusion",entity:"/m/06r0ps",alias:null},
  {name:"Mania",entity:"/m/05417",alias:null},
  {name:"Measles",entity:"/m/0g2gb",alias:null},
  {name:"Mechanism of action",entity:"/m/0d2x17",alias:null},
  {name:"Medulloblastoma",entity:"/m/0bbl62",alias:null},
  {name:"Megacolon",entity:"/m/07qctz",alias:null},
  {name:"Melancholia",entity:"/m/057vp",alias:null},
  {name:"Melanocytic nevus",entity:"/m/0dc28",alias:null},
  {name:"Melanoma",entity:"/m/035b2g",alias:null},
  {name:"Melasma",entity:"/m/04z9bf",alias:null},
  {name:"Melena",entity:"/m/02n2tg",alias:null},
  {name:"Meningism",entity:"/m/04v_ml",alias:null},
  {name:"Meningitis",entity:"/m/09d11",alias:null},
  {name:"Menorrhagia",entity:"/m/031c33",alias:null},
  {name:"Menstrual disorder",entity:"/m/0b5pfn",alias:null},
  {name:"Mental disorder",entity:"/m/04x4r",alias:null},
  {name:"Metabolic acidosis",entity:"/m/04tksh",alias:null},
  {name:"Metabolic alkalosis",entity:"/m/025sktj",alias:null},
  {name:"Metaplasia",entity:"/m/059h7h",alias:null},
  {name:"Metastatic liver disease",entity:"/m/047cg9y",alias:null},
  {name:"Methemoglobinemia",entity:"/m/01npzs",alias:null},
  {name:"Metrorrhagia",entity:"/m/08_6kp",alias:null},
  {name:"Microalbuminuria",entity:"/m/07y7r4",alias:null},
  {name:"Microcalcification",entity:"/m/095qsg",alias:null},
  {name:"Microcephaly",entity:"/m/01hrbm",alias:null},
  {name:"Micromastia",entity:"/m/09pv41",alias:null},
  {name:"Middle back pain",entity:"/m/09rlb3",alias:null},
  {name:"Migraine",entity:"/m/05904",alias:null},
  {name:"Milium",entity:"/m/0527by",alias:null},
  {name:"Miosis",entity:"/m/03smvc",alias:null},
  {name:"Mitral valve prolapse",entity:"/m/02np4g",alias:null},
  {name:"Mood disorder",entity:"/m/0drn8",alias:null},
  {name:"Mood swing",entity:"/m/022y3k",alias:null},
  {name:"Moon face",entity:"/m/02prmbk",alias:null},
  {name:"Morning sickness",entity:"/m/01j9hg",alias:null},
  {name:"Morphea",entity:"/m/09lkp9",alias:null},
  {name:"Motion sickness",entity:"/m/0gxcc",alias:null},
  {name:"Mouth breathing",entity:"/m/08gzn6",alias:null},
  {name:"Movement disorders",entity:"/m/03whtc",alias:null},
  {name:"Multiple organ dysfunction syndrome",entity:"/m/03hnn3",alias:null},
  {name:"Multiple sclerosis",entity:"/m/0dcqh",alias:null},
  {name:"Murphy's sign",entity:"/m/071ttc",alias:null},
  {name:"Muscle atrophy",entity:"/m/0dds0h",alias:null},
  {name:"Muscle contraction",entity:"/m/046xb9",alias:null},
  {name:"Muscle pain",entity:"/m/013677",alias:null},
  {name:"Muscle weakness",entity:"/m/0927l7",alias:null},
  {name:"Muteness",entity:"/m/0287zzh",alias:null},
  {name:"Mydriasis",entity:"/m/01dhgh",alias:null},
  {name:"Myelodysplastic syndrome",entity:"/m/019gky",alias:null},
  {name:"Myelopathy",entity:"/m/04_1ntx",alias:null},
  {name:"Myocardial infarction",entity:"/m/0gk4g",alias:"Heart attack"},
  {name:"Myoclonus",entity:"/m/02_mfs",alias:null},
  {name:"Myopathy",entity:"/m/058k0k",alias:null},
  {name:"Myxedema",entity:"/m/02wp6c",alias:null},
  {name:"Nail clubbing",entity:"/m/02qbnn",alias:null},
  {name:"Narcissistic personality disorder",entity:"/m/019jq7",alias:null},
  {name:"Nasal congestion",entity:"/m/05s5v6",alias:null},
  {name:"Nasal polyp",entity:"/m/034hsj",alias:null},
  {name:"Nasal septum deviation",entity:"/m/05cz29",alias:null},
  {name:"Nausea",entity:"/m/0gxb2",alias:null},
  {name:"Near-sightedness",entity:"/m/0m2w3",alias:null},
  {name:"Neck mass",entity:"/m/0crhp0y",alias:null},
  {name:"Neck pain",entity:"/m/02r3cvb",alias:null},
  {name:"Neck spasm",entity:"/m/043s7zg",alias:null},
  {name:"Neck stiffness",entity:"/m/0bmgh43",alias:null},
  {name:"Necrosis",entity:"/m/09yql",alias:null},
  {name:"Necrotizing fasciitis",entity:"/m/01q6nb",alias:null},
  {name:"Neonatal jaundice",entity:"/m/074hph",alias:null},
  {name:"Nephritic syndrome",entity:"/m/06yg6t",alias:null},
  {name:"Nephrotic syndrome",entity:"/m/01n597",alias:null},
  {name:"Nerve injury",entity:"/m/02pm604",alias:null},
  {name:"Neuralgia",entity:"/m/05kzxm",alias:null},
  {name:"Neurofibroma",entity:"/m/08gljx",alias:null},
  {name:"Neuropathic Pain",entity:"/m/09gnhp2",alias:null},
  {name:"Neutrophilia",entity:"/m/01jjvn",alias:null},
  {name:"Night sweats",entity:"/m/04klgqw",alias:null},
  {name:"Night terror",entity:"/m/0272zb",alias:null},
  {name:"Nightmare",entity:"/m/0cjgc",alias:null},
  {name:"Nipple discharge",entity:"/m/04696g",alias:null},
  {name:"Nocturia",entity:"/m/0868jh",alias:null},
  {name:"Nocturnal enuresis",entity:"/m/01wy8y",alias:null},
  {name:"Nodule",entity:"/m/0905_p",alias:null},
  {name:"Nosebleed",entity:"/m/02zbth",alias:null},
  {name:"Nyctalopia",entity:"/m/04970l",alias:null},
  {name:"Nystagmus",entity:"/m/01skrq",alias:null},
  {name:"Obesity",entity:"/m/0fltx",alias:null},
  {name:"Obtundation",entity:"/m/0b0kl9",alias:null},
  {name:"Odynophagia",entity:"/m/0997hp",alias:null},
  {name:"Oligomenorrhea",entity:"/m/04yyq8",alias:null},
  {name:"Oligospermia",entity:"/m/06z9sn",alias:null},
  {name:"Oliguria",entity:"/m/04b1kq",alias:null},
  {name:"Onychocryptosis",entity:"/m/0476hh",alias:null},
  {name:"Onychorrhexis",entity:"/m/090ryn",alias:null},
  {name:"Opisthotonus",entity:"/m/04bm26",alias:null},
  {name:"Optic neuritis",entity:"/m/05pzb",alias:null},
  {name:"Orthopnea",entity:"/m/02lmp9",alias:null},
  {name:"Orthostatic hypotension",entity:"/m/0pv4d",alias:null},
  {name:"Ossification",entity:"/m/050qm0",alias:null},
  {name:"Osteoarthritis",entity:"/m/02jf6f",alias:null},
  {name:"Osteomalacia",entity:"/m/02npcz",alias:null},
  {name:"Osteopenia",entity:"/m/04zh7_m",alias:null},
  {name:"Osteophyte",entity:"/m/03kb14",alias:null},
  {name:"Osteoporosis",entity:"/m/05mdx",alias:null},
  {name:"Otitis",entity:"/m/0743mf",alias:null},
  {name:"Otitis externa",entity:"/m/04w68t",alias:null},
  {name:"Ovarian cancer",entity:"/m/025hl8",alias:null},
  {name:"Ovarian cyst",entity:"/m/01xyfj",alias:null},
  {name:"Overweight",entity:"/m/01t6qr",alias:null},
  {name:"Pain",entity:"/m/062t2",alias:null},
  {name:"Pallor",entity:"/m/03skrx",alias:null},
  {name:"Palpitations",entity:"/m/029ggh",alias:null},
  {name:"Pancreatitis",entity:"/m/0h1wz",alias:null},
  {name:"Pancytopenia",entity:"/m/063jn6",alias:null},
  {name:"Panic",entity:"/m/01t09s",alias:null},
  {name:"Panic attack",entity:"/m/0g88b",alias:null},
  {name:"Papilledema",entity:"/m/01c9lj",alias:null},
  {name:"Papule",entity:"/m/04xgtj",alias:null},
  {name:"Paralysis",entity:"/m/05sj8",alias:null},
  {name:"Paranoia",entity:"/m/063zb",alias:null},
  {name:"Paraplegia",entity:"/m/0251gx",alias:null},
  {name:"Paresis",entity:"/m/01ny_g",alias:null},
  {name:"Paresthesia",entity:"/m/023m3v",alias:null},
  {name:"Parkinsonism",entity:"/m/0dcs4",alias:null},
  {name:"Paroxysmal nocturnal dyspnea",entity:"/m/0gttzbm",alias:null},
  {name:"Pathological lying",entity:"/m/089sp6",alias:null},
  {name:"Peanut allergy",entity:"/m/085pjw",alias:null},
  {name:"Pectus carinatum",entity:"/m/05l8yp",alias:null},
  {name:"Pectus excavatum",entity:"/m/03750f",alias:null},
  {name:"Pelvic inflammatory disease",entity:"/m/064fq",alias:null},
  {name:"Pelvic organ prolapse",entity:"/m/07kyr1",alias:null},
  {name:"Pericardial effusion",entity:"/m/08z994",alias:null},
  {name:"Pericarditis",entity:"/m/032snl",alias:null},
  {name:"Periorbital dark circles",entity:"/m/04cbz5",alias:null},
  {name:"Periorbital puffiness",entity:"/m/027pqtp",alias:null},
  {name:"Peripheral edema",entity:"/m/06v6kk",alias:null},
  {name:"Peripheral neuropathy",entity:"/m/02w1fx",alias:null},
  {name:"Peritonsillar abscess",entity:"/m/04b586",alias:null},
  {name:"Persecutory delusion",entity:"/m/09g6vr0",alias:null},
  {name:"Persistent truncus arteriosus",entity:"/m/07dlyv",alias:null},
  {name:"Persistent vegetative state",entity:"/m/01rvjp",alias:null},
  {name:"Perspiration",entity:"/m/0k9qw",alias:null},
  {name:"Pertussis",entity:"/m/016ygs",alias:"Whooping cough"},
  {name:"Petechia",entity:"/m/04c2n0",alias:null},
  {name:"Pharyngitis",entity:"/m/01gkcc",alias:null},
  {name:"Phlebitis",entity:"/m/03rwrr",alias:null},
  {name:"Phlegm",entity:"/m/01s3l8",alias:null},
  {name:"Phobia",entity:"/m/05tf3",alias:null},
  {name:"Phocomelia",entity:"/m/0jzx0",alias:null},
  {name:"Phosphene",entity:"/m/038s2d",alias:null},
  {name:"Photodermatitis",entity:"/m/03c2dk",alias:null},
  {name:"Photophobia",entity:"/m/02lv8g",alias:null},
  {name:"Photopsia",entity:"/m/09p809",alias:null},
  {name:"Phyllodes tumor",entity:"/m/07mvcp",alias:null},
  {name:"Pica",entity:"/m/01b8zz",alias:null},
  {name:"Placental abruption",entity:"/m/0508hk",alias:null},
  {name:"Pneumonia",entity:"/m/0dq9p",alias:null},
  {name:"Pneumothorax",entity:"/m/01q1sz",alias:null},
  {name:"Poliomyelitis",entity:"/m/068p_",alias:null},
  {name:"Polyarthritis",entity:"/m/06hxx0",alias:null},
  {name:"Polycythemia",entity:"/m/02k88f",alias:null},
  {name:"Polydipsia",entity:"/m/02v6kp",alias:null},
  {name:"Polyneuropathy",entity:"/m/03cx49",alias:null},
  {name:"Polyphagia",entity:"/m/03gncj",alias:null},
  {name:"Polyuria",entity:"/m/01m3h8",alias:null},
  {name:"Portal hypertension",entity:"/m/034h9r",alias:null},
  {name:"Post herniorraphy pain syndrome",entity:"/m/0ggb_w",alias:null},
  {name:"Post-concussion syndrome",entity:"/m/09qljf",alias:null},
  {name:"Post-nasal drip",entity:"/m/0615kf",alias:null},
  {name:"Postictal state",entity:"/m/0ctw0q",alias:null},
  {name:"Postorgasmic illness syndrome",entity:"/m/05p5_7y",alias:null},
  {name:"Postural orthostatic tachycardia syndrome",entity:"/m/04l6qx",alias:null},
  {name:"Pre-eclampsia",entity:"/m/025lwc",alias:null},
  {name:"Precocious puberty",entity:"/m/02_nx2",alias:null},
  {name:"Prehypertension",entity:"/m/03cz_hv",alias:null},
  {name:"Premature atrial contraction",entity:"/m/04kgzqg",alias:null},
  {name:"Premature ejaculation",entity:"/m/01qqp1",alias:null},
  {name:"Premature ventricular contraction",entity:"/m/01hjkt",alias:null},
  {name:"Premenstrual syndrome",entity:"/m/01fxrj",alias:null},
  {name:"Pressure ulcer",entity:"/m/03ncwn",alias:null},
  {name:"Priapism",entity:"/m/0ldwy",alias:null},
  {name:"Proctitis",entity:"/m/06rf7m",alias:null},
  {name:"Prodrome",entity:"/m/01k7nc",alias:null},
  {name:"Prognathism",entity:"/m/06g3nz",alias:null},
  {name:"Prolapse",entity:"/m/01jcd6",alias:null},
  {name:"Prostate cancer",entity:"/m/0m32h",alias:null},
  {name:"Proteinuria",entity:"/m/012zf3",alias:null},
  {name:"Prurigo",entity:"/m/0gk2pb",alias:null},
  {name:"Pruritus ani",entity:"/m/02pq2mj",alias:null},
  {name:"Pseudarthrosis",entity:"/m/05_3zr",alias:null},
  {name:"Pseudobulbar affect",entity:"/m/04lg5mq",alias:null},
  {name:"Psoriasis",entity:"/m/0pv62",alias:null},
  {name:"Psychomotor agitation",entity:"/m/05p8sj",alias:null},
  {name:"Psychosis",entity:"/m/063yv",alias:null},
  {name:"Psychotic break",entity:"/m/03l9p5",alias:null},
  {name:"Ptosis",entity:"/m/0gdsn5",alias:null},
  {name:"Pulmonary edema",entity:"/m/0260ph",alias:null},
  {name:"Pulmonary embolism",entity:"/m/01ddth",alias:null},
  {name:"Pulmonary Hypertension",entity:"/m/031wv7",alias:null},
  {name:"Pulsus paradoxus",entity:"/m/087c0d",alias:null},
  {name:"Purpura",entity:"/m/04c2m8",alias:null},
  {name:"Pus",entity:"/m/01s2ly",alias:null},
  {name:"Pustule",entity:"/m/01fxyp",alias:null},
  {name:"Pyelonephritis",entity:"/m/04_rt_",alias:null},
  {name:"Pyoderma gangrenosum",entity:"/m/08s9h0",alias:null},
  {name:"Pyuria",entity:"/m/08bp74",alias:null},
  {name:"Q fever",entity:"/m/0fm4r",alias:null},
  {name:"Rabies",entity:"/m/0fsd1",alias:null},
  {name:"Radiculopathy",entity:"/m/02pfkpc",alias:null},
  {name:"Raynaud syndrome",entity:"/m/02v2jk",alias:null},
  {name:"Rectal discharge",entity:"/m/0dl9s9j",alias:null},
  {name:"Rectal pain",entity:"/m/0b74tbc",alias:null},
  {name:"Rectal prolapse",entity:"/m/03080q",alias:null},
  {name:"Rectal tenesmus",entity:"/m/04yfk_",alias:null},
  {name:"Red eye",entity:"/m/04pxm5",alias:null},
  {name:"Reduced affect display",entity:"/m/08z6vk",alias:null},
  {name:"Regurgitation",entity:"/m/0fv217",alias:null},
  {name:"Renal colic",entity:"/m/06phzx",alias:null},
  {name:"Renal cyst",entity:"/m/0b77v22",alias:null},
  {name:"Respiratory acidosis",entity:"/m/04tkvk",alias:null},
  {name:"Respiratory arrest",entity:"/m/037c4l",alias:null},
  {name:"Respiratory distress",entity:"/m/0jwzzd9",alias:null},
  {name:"Respiratory failure",entity:"/m/019dmc",alias:null},
  {name:"Respiratory tract infection",entity:"/m/0117wzhd",alias:null},
  {name:"Restless legs syndrome",entity:"/m/01jyld",alias:null},
  {name:"Retching",entity:"/m/02rjt8c",alias:null},
  {name:"Retrograde amnesia",entity:"/m/040z8c",alias:null},
  {name:"Rheum",entity:"/m/02p1kqs",alias:null},
  {name:"Rheumatoid arthritis",entity:"/m/06g7c",alias:null},
  {name:"Rhinitis",entity:"/m/02mdz9",alias:null},
  {name:"Rhinophyma",entity:"/m/0dyhxj",alias:null},
  {name:"Rhinorrhea",entity:"/m/06p_bp",alias:null},
  {name:"Rhonchi",entity:"/m/09jv3z",alias:null},
  {name:"Ringworm",entity:"/m/023yjf",alias:null},
  {name:"Rubella",entity:"/m/0175qw",alias:null},
  {name:"Rumination",entity:"/m/04grp19",alias:null},
  {name:"Running amok",entity:"/m/014sp",alias:null},
  {name:"Scabies",entity:"/m/074kq",alias:null},
  {name:"Scarlet Fever",entity:"/m/0mzt3",alias:null},
  {name:"Schistosomiasis",entity:"/m/01b4_7",alias:null},
  {name:"Sciatica",entity:"/m/01_wxr",alias:null},
  {name:"Scleritis",entity:"/m/08gppk",alias:null},
  {name:"Scleroderma",entity:"/m/05m_zv2",alias:null},
  {name:"Scoliosis",entity:"/m/0yvgr",alias:null},
  {name:"Scotoma",entity:"/m/03gzmf",alias:null},
  {name:"Seborrheic dermatitis",entity:"/m/02cvvl",alias:null},
  {name:"Second-degree atrioventricular block",entity:"/m/031s_5",alias:null},
  {name:"Self-destructive behaviour",entity:"/m/026qvtc",alias:null},
  {name:"Self-harm",entity:"/m/013cc9",alias:null},
  {name:"Sensorineural hearing loss",entity:"/m/04fmz1",alias:null},
  {name:"Sepsis",entity:"/m/014w_8",alias:null},
  {name:"Septic shock",entity:"/m/029mr9",alias:null},
  {name:"Serotonin syndrome",entity:"/m/079hg",alias:null},
  {name:"Sexual addiction",entity:"/m/05xsp8",alias:null},
  {name:"Sexual dysfunction",entity:"/m/0255qr",alias:null},
  {name:"Shallow breathing",entity:"/m/08wqjw",alias:null},
  {name:"Shigellosis",entity:"/m/0mzxc",alias:null},
  {name:"Shingles",entity:"/m/029577",alias:null},
  {name:"Shivering",entity:"/m/04fv7w",alias:null},
  {name:"Shock",entity:"/m/012n6d",alias:null},
  {name:"Short bowel syndrome",entity:"/m/04mr0d",alias:null},
  {name:"Short stature",entity:"/m/06y96j",alias:null},
  {name:"Shortness of breath",entity:"/m/01cdt5",alias:null},
  {name:"Shyness",entity:"/m/01dl7h",alias:null},
  {name:"Single transverse palmar crease",entity:"/m/04fl9l",alias:null},
  {name:"Sinus bradycardia",entity:"/m/06rsk8",alias:null},
  {name:"Sinus tachycardia",entity:"/m/06rsny",alias:null},
  {name:"Sinusitis",entity:"/m/072hv",alias:null},
  {name:"Skin fissure",entity:"/m/0gmcs4z",alias:null},
  {name:"Skin infection",entity:"/m/05m_2vv",alias:null},
  {name:"Skin rash",entity:"/m/0v4rnx",alias:null},
  {name:"Skin tag",entity:"/m/0fktd",alias:null},
  {name:"Sleep apnea",entity:"/m/071d3",alias:null},
  {name:"Sleep deprivation",entity:"/m/017tfz",alias:null},
  {name:"Sleep disorder",entity:"/m/0cnmb",alias:null},
  {name:"Sleep paralysis",entity:"/m/01jb2q",alias:null},
  {name:"Slipped capital femoral epiphysis",entity:"/m/07bztx",alias:null},
  {name:"Smallpox",entity:"/m/06vr2",alias:null},
  {name:"Sneeze",entity:"/m/01hsr_",alias:null},
  {name:"Snoring",entity:"/m/01d3sd",alias:null},
  {name:"Somnolence",entity:"/m/0311pr",alias:null},
  {name:"Sore throat",entity:"/m/0b76bty",alias:null},
  {name:"Spasm",entity:"/m/04zjnsf",alias:null},
  {name:"Spasmodic dysphonia",entity:"/m/07d0js",alias:null},
  {name:"Spasticity",entity:"/m/0p9n0",alias:null},
  {name:"Speech delay",entity:"/m/0726rf",alias:null},
  {name:"Speech disorder",entity:"/m/0133cx",alias:null},
  {name:"Spider angioma",entity:"/m/090j35",alias:null},
  {name:"Spinal tumor",entity:"/m/03znrn",alias:null},
  {name:"Splenomegaly",entity:"/m/03zqp2",alias:null},
  {name:"Splitting",entity:"/m/02q48gs",alias:null},
  {name:"Sputum",entity:"/m/01jmfg",alias:null},
  {name:"Stage fright",entity:"/m/02v58l",alias:null},
  {name:"Starvation",entity:"/m/01flyj",alias:null},
  {name:"Stasis dermatitis",entity:"/m/04q_81",alias:null},
  {name:"Status epilepticus",entity:"/m/06382k",alias:null},
  {name:"Steatorrhea",entity:"/m/03_7qy",alias:null},
  {name:"Stenosis",entity:"/m/032llx",alias:null},
  {name:"Stereotypy",entity:"/m/0dg_lc",alias:null},
  {name:"Stertor",entity:"/m/0d4b5s",alias:null},
  {name:"Stiffness",entity:"/m/02dzkc",alias:null},
  {name:"Stomach rumble",entity:"/m/01g90h",alias:null},
  {name:"Stomatitis",entity:"/m/06jf34",alias:null},
  {name:"Strabismus",entity:"/m/02s645",alias:null},
  {name:"Stress",entity:"/m/012lyw",alias:null},
  {name:"Stretch marks",entity:"/m/056g4k",alias:null},
  {name:"Stridor",entity:"/m/05rtnw",alias:null},
  {name:"Stroke",entity:"/m/02y0js",alias:null},
  {name:"Stunted growth",entity:"/m/09g54b",alias:null},
  {name:"Stupor",entity:"/m/08gxks",alias:null},
  {name:"Stuttering",entity:"/m/070yw",alias:null},
  {name:"Subcutaneous emphysema",entity:"/m/0464mv7",alias:null},
  {name:"Substance abuse",entity:"/m/0p_cr",alias:null},
  {name:"Substance dependence",entity:"/m/0466pc0",alias:null},
  {name:"Sudden cardiac death",entity:"/m/0d_mn0",alias:null},
  {name:"Sunburn",entity:"/m/015slp",alias:null},
  {name:"Sundowning",entity:"/m/04jmkz7",alias:null},
  {name:"Superior vena cava syndrome",entity:"/m/04tr95",alias:null},
  {name:"Supraventricular tachycardia",entity:"/m/03k_qd",alias:null},
  {name:"Swelling",entity:"/m/09bdp3",alias:null},
  {name:"Swollen feet",entity:"/m/0dl9t52",alias:null},
  {name:"Swollen lymph nodes",entity:"/m/03yzl6",alias:null},
  {name:"Sydenham's chorea",entity:"/m/04jr23",alias:null},
  {name:"Syncope",entity:"/m/04jpj9y",alias:null},
  {name:"Syndrome of inappropriate antidiuretic hormone secretion",entity:"/m/03zzcc",alias:null},
  {name:"Synechia",entity:"/m/037xdl",alias:null},
  {name:"Synovitis",entity:"/m/07yqh1",alias:null},
  {name:"systemic lupus erythematosus",entity:"/m/04nz3",alias:"Lupus"},
  {name:"Systolic heart murmur",entity:"/m/05b5h0l",alias:null},
  {name:"Tachycardia",entity:"/m/0156z4",alias:null},
  {name:"Tachypnea",entity:"/m/03w94wq",alias:null},
  {name:"Tanning dependence",entity:"/m/03crfch",alias:null},
  {name:"Tardive dyskinesia",entity:"/m/01vl0h",alias:null},
  {name:"Telangiectasia",entity:"/m/0500_3",alias:null},
  {name:"Tenderness",entity:"/m/03m4j90",alias:null},
  {name:"Tendinitis",entity:"/m/01kcp2",alias:null},
  {name:"Tenosynovitis",entity:"/m/01nzjv",alias:null},
  {name:"Teratospermia",entity:"/m/0523q1y",alias:null},
  {name:"Testicular cancer",entity:"/m/01rt5h",alias:null},
  {name:"Tetanic contraction",entity:"/m/026m6v",alias:null},
  {name:"Tetanus",entity:"/m/0cfb2",alias:null},
  {name:"Tetany",entity:"/m/02pnp2q",alias:null},
  {name:"Tetralogy of Fallot",entity:"/m/01k4yc",alias:null},
  {name:"Tetraplegia",entity:"/m/01bpld",alias:null},
  {name:"Thirst",entity:"/m/02jx54",alias:null},
  {name:"Thought disorder",entity:"/m/01p1zm",alias:null},
  {name:"Throat irritation",entity:"/m/0b6kt_8",alias:null},
  {name:"Thrombocytopenia",entity:"/m/02kgmg",alias:null},
  {name:"Thrombocytosis",entity:"/m/03btxg",alias:null},
  {name:"Thrombosis",entity:"/m/018_pw",alias:null},
  {name:"Thyroid disease",entity:"/m/05n00c6",alias:null},
  {name:"Thyroid nodule",entity:"/m/05l6q9",alias:null},
  {name:"Tic",entity:"/m/02gpbb",alias:null},
  {name:"Tinel's sign",entity:"/m/04bn2w",alias:null},
  {name:"Tinnitus",entity:"/m/0pv6y",alias:null},
  {name:"Tonsillitis",entity:"/m/03ng0t",alias:null},
  {name:"Tooth decay",entity:"/m/025j63",alias:null},
  {name:"Tooth loss",entity:"/m/02q28kg",alias:null},
  {name:"Toothache",entity:"/m/045c85",alias:null},
  {name:"Tophus",entity:"/m/04bm_r",alias:null},
  {name:"Torticollis",entity:"/m/01q136",alias:null},
  {name:"Tourette syndrome",entity:"/m/0fm5n",alias:null},
  {name:"Transudate",entity:"/m/02wv9sp",alias:null},
  {name:"Tremor",entity:"/m/09d28",alias:null},
  {name:"Trichomoniasis",entity:"/m/0m72x",alias:null},
  {name:"Trichoptilosis",entity:"/m/0269y8n",alias:null},
  {name:"Trichotillomania",entity:"/m/0h_8y",alias:null},
  {name:"Trismus",entity:"/m/01fgvy",alias:null},
  {name:"Tuberculosis",entity:"/m/07jwr",alias:null},
  {name:"Tunnel vision",entity:"/m/01z0b9",alias:null},
  {name:"Type 2 diabetes",entity:"/m/0146bp",alias:null},
  {name:"Typhoid fever",entity:"/m/07s4l",alias:null},
  {name:"Typhus",entity:"/m/057xn02",alias:null},
  {name:"Ulcerative colitis",entity:"/m/0h1r3",alias:null},
  {name:"Unconsciousness",entity:"/m/04kfhc9",alias:null},
  {name:"Underweight",entity:"/m/0844zv",alias:null},
  {name:"Upper gastrointestinal bleeding",entity:"/m/02n2jh",alias:null},
  {name:"Upper respiratory tract infection",entity:"/m/02wmyj",alias:null},
  {name:"Uremia",entity:"/m/02f8hm",alias:null},
  {name:"Urethritis",entity:"/m/07wvs",alias:null},
  {name:"Urinary incontinence",entity:"/m/018h13",alias:null},
  {name:"Urinary retention",entity:"/m/045y32",alias:null},
  {name:"Urinary tract infection",entity:"/m/07x16",alias:null},
  {name:"Urinary urgency",entity:"/m/0fvh3d",alias:null},
  {name:"Uterine contraction",entity:"/m/02shy2",alias:null},
  {name:"Uveitis",entity:"/m/040_ch",alias:null},
  {name:"Vaginal bleeding",entity:"/m/055k6m",alias:null},
  {name:"Vaginal discharge",entity:"/m/07k9rmb",alias:null},
  {name:"Vaginal flatulence",entity:"/m/017ts5",alias:null},
  {name:"Vaginitis",entity:"/m/01vcpr",alias:null},
  {name:"Varicose veins",entity:"/m/081dp",alias:null},
  {name:"Vascular occlusion",entity:"/m/0b6h30_",alias:null},
  {name:"Vasculitis",entity:"/m/0317gc",alias:null},
  {name:"Vasoconstriction",entity:"/m/02wv6ss",alias:null},
  {name:"Vasodilation",entity:"/m/0fkcf",alias:null},
  {name:"Vasovagal syncope",entity:"/m/039y0d",alias:null},
  {name:"Vegetation",entity:"/m/04gp557",alias:null},
  {name:"Vegetative-vascular dystonia",entity:"/m/0wbjrwb",alias:null},
  {name:"Venous stasis",entity:"/m/04jj6yp",alias:null},
  {name:"Ventricular septal defect",entity:"/m/03k28n",alias:null},
  {name:"Ventricular tachycardia",entity:"/m/025v410",alias:null},
  {name:"Vertigo",entity:"/m/07rwf2",alias:null},
  {name:"Viral pneumonia",entity:"/m/07fn78",alias:null},
  {name:"Virilization",entity:"/m/032zt5",alias:null},
  {name:"Vision disorder",entity:"/m/04jmzm5",alias:null},
  {name:"Visual acuity",entity:"/m/02_g1v",alias:null},
  {name:"Visual snow",entity:"/m/0379jz",alias:null},
  {name:"Vitamin B12 deficiency",entity:"/m/02x2xmj",alias:null},
  {name:"Vitamin deficiency",entity:"/m/0q42v",alias:null},
  {name:"Vitiligo",entity:"/m/0hg1d",alias:null},
  {name:"Voice change",entity:"/m/0hzmhkt",alias:null},
  {name:"Vomiting",entity:"/m/012qjw",alias:null},
  {name:"Vulvar vestibulitis",entity:"/m/0h7q7v0",alias:null},
  {name:"Vulvitis",entity:"/m/06qjbg",alias:null},
  {name:"Vulvodynia",entity:"/m/08099",alias:null},
  {name:"Wanderlust",entity:"/m/038ytw",alias:null},
  {name:"Wart",entity:"/m/086hz",alias:null},
  {name:"Water retention",entity:"/m/05s_d8r",alias:null},
  {name:"Weakness",entity:"/m/0119nqlg",alias:null},
  {name:"Wheeze",entity:"/m/07mzm6",alias:null},
  {name:"Widow's peak",entity:"/m/03d23v",alias:null},
  {name:"Wound",entity:"/m/01xrk2",alias:null},
  {name:"Wrinkle",entity:"/m/02_x63",alias:null},
  {name:"Xanthoma",entity:"/m/02gl_t",alias:null},
  {name:"Xeroderma",entity:"/m/08xv95",alias:null},
  {name:"Xerophthalmia",entity:"/m/0517c6",alias:null},
  {name:"Xerostomia",entity:"/m/04d7y3",alias:null},
  {name:"Yellow Fever",entity:"/m/087z2",alias:null},
  {name:"Zika virus",entity:"/m/080m_5j",alias:null}
];

export const countries = [
  {iso:"world",name:"World", "article": true},
  {iso:"AF",name:"Afghanistan", "article": false},
  {iso:"AX",name:"Åland", "article": false},
  {iso:"AL",name:"Albania", "article": false},
  {iso:"DZ",name:"Algeria", "article": false},
  {iso:"AS",name:"American Samoa", "article": true},
  {iso:"AD",name:"Andorra", "article": false},
  {iso:"AO",name:"Angola", "article": false},
  {iso:"AI",name:"Anguilla", "article": false},
  {iso:"AQ",name:"Antarctica", "article": false},
  {iso:"AG",name:"Antigua and Barbuda", "article": false},
  {iso:"AR",name:"Argentina", "article": false},
  {iso:"AM",name:"Armenia", "article": false},
  {iso:"AW",name:"Aruba", "article": false},
  {iso:"AU",name:"Australia", "article": false},
  {iso:"AT",name:"Austria", "article": false},
  {iso:"AZ",name:"Azerbaijan", "article": false},
  {iso:"BS",name:"Bahamas", "article": true},
  {iso:"BH",name:"Bahrain", "article": false},
  {iso:"BD",name:"Bangladesh", "article": false},
  {iso:"BB",name:"Barbados", "article": false},
  {iso:"BY",name:"Belarus", "article": false},
  {iso:"BE",name:"Belgium", "article": false},
  {iso:"BZ",name:"Belize", "article": false},
  {iso:"BJ",name:"Benin", "article": false},
  {iso:"BM",name:"Bermuda", "article": false},
  {iso:"BT",name:"Bhutan", "article": false},
  {iso:"BO",name:"Bolivia", "article": false},
  {iso:"BQ",name:"Bonaire", "article": false},
  {iso:"BA",name:"Bosnia and Herzegovina", "article": false},
  {iso:"BW",name:"Botswana", "article": false},
  {iso:"BV",name:"Bouvet Island", "article": false},
  {iso:"BR",name:"Brazil", "article": false},
  {iso:"IO",name:"British Indian Ocean Territory", "article": true},
  {iso:"VG",name:"British Virgin Islands", "article": true},
  {iso:"BN",name:"Brunei", "article": false},
  {iso:"BG",name:"Bulgaria", "article": false},
  {iso:"BF",name:"Burkina Faso", "article": false},
  {iso:"BI",name:"Burundi", "article": false},
  {iso:"KH",name:"Cambodia", "article": false},
  {iso:"CM",name:"Cameroon", "article": false},
  {iso:"CA",name:"Canada", "article": false},
  {iso:"CV",name:"Cape Verde", "article": false},
  {iso:"KY",name:"Cayman Islands", "article": false},
  {iso:"CF",name:"Central African Republic", "article": false},
  {iso:"TD",name:"Chad", "article": false},
  {iso:"CL",name:"Chile", "article": false},
  {iso:"CN",name:"China", "article": false},
  {iso:"CX",name:"Christmas Island", "article": false},
  {iso:"CC",name:"Cocos [Keeling] Islands", "article": false},
  {iso:"CO",name:"Colombia", "article": false},
  {iso:"KM",name:"Comoros", "article": false},
  {iso:"CK",name:"Cook Islands", "article": false},
  {iso:"CR",name:"Costa Rica", "article": false},
  {iso:"HR",name:"Croatia", "article": false},
  {iso:"CU",name:"Cuba", "article": false},
  {iso:"CW",name:"Curacao", "article": false},
  {iso:"CY",name:"Cyprus", "article": false},
  {iso:"CZ",name:"Czechia", "article": false},
  {iso:"CD",name:"Democratic Republic of the Congo", "article": false},
  {iso:"DK",name:"Denmark", "article": false},
  {iso:"DJ",name:"Djibouti", "article": false},
  {iso:"DM",name:"Dominica", "article": false},
  {iso:"DO",name:"Dominican Republic", "article": false},
  {iso:"TL",name:"East Timor", "article": false},
  {iso:"EC",name:"Ecuador", "article": false},
  {iso:"EG",name:"Egypt", "article": false},
  {iso:"SV",name:"El Salvador", "article": false},
  {iso:"GQ",name:"Equatorial Guinea", "article": false},
  {iso:"ER",name:"Eritrea", "article": false},
  {iso:"EE",name:"Estonia", "article": false},
  {iso:"ET",name:"Ethiopia", "article": false},
  {iso:"FK",name:"Falkland Islands", "article": false},
  {iso:"FO",name:"Faroe Islands", "article": false},
  {iso:"FJ",name:"Fiji", "article": false},
  {iso:"FI",name:"Finland", "article": false},
  {iso:"FR",name:"France", "article": false},
  {iso:"GF",name:"French Guiana", "article": false},
  {iso:"PF",name:"French Polynesia", "article": false},
  {iso:"TF",name:"French Southern Territories", "article": false},
  {iso:"GA",name:"Gabon", "article": false},
  {iso:"GM",name:"Gambia", "article": false},
  {iso:"GE",name:"Georgia", "article": false},
  {iso:"DE",name:"Germany", "article": false},
  {iso:"GH",name:"Ghana", "article": false},
  {iso:"GI",name:"Gibraltar", "article": false},
  {iso:"GR",name:"Greece", "article": false},
  {iso:"GL",name:"Greenland", "article": false},
  {iso:"GD",name:"Grenada", "article": false},
  {iso:"GP",name:"Guadeloupe", "article": false},
  {iso:"GU",name:"Guam", "article": false},
  {iso:"GT",name:"Guatemala", "article": false},
  {iso:"GG",name:"Guernsey", "article": false},
  {iso:"GN",name:"Guinea", "article": false},
  {iso:"GW",name:"Guinea-Bissau", "article": false},
  {iso:"GY",name:"Guyana", "article": false},
  {iso:"HT",name:"Haiti", "article": false},
  {iso:"HM",name:"Heard Island and McDonald Islands", "article": false},
  {iso:"HN",name:"Honduras", "article": false},
  {iso:"HK",name:"Hong Kong", "article": false},
  {iso:"HU",name:"Hungary", "article": false},
  {iso:"IS",name:"Iceland", "article": false},
  {iso:"IN",name:"India", "article": false},
  {iso:"ID",name:"Indonesia", "article": false},
  {iso:"IR",name:"Iran", "article": false},
  {iso:"IQ",name:"Iraq", "article": false},
  {iso:"IE",name:"Ireland", "article": false},
  {iso:"IM",name:"Isle of Man", "article": false},
  {iso:"IL",name:"Israel", "article": false},
  {iso:"IT",name:"Italy", "article": false},
  {iso:"CI",name:"Ivory Coast", "article": false},
  {iso:"JM",name:"Jamaica", "article": false},
  {iso:"JP",name:"Japan", "article": false},
  {iso:"JE",name:"Jersey", "article": false},
  {iso:"JO",name:"Jordan", "article": false},
  {iso:"KZ",name:"Kazakhstan", "article": false},
  {iso:"KE",name:"Kenya", "article": false},
  {iso:"KI",name:"Kiribati", "article": false},
  {iso:"XK",name:"Kosovo", "article": false},
  {iso:"KW",name:"Kuwait", "article": false},
  {iso:"KG",name:"Kyrgyzstan", "article": false},
  {iso:"LA",name:"Laos", "article": false},
  {iso:"LV",name:"Latvia", "article": false},
  {iso:"LB",name:"Lebanon", "article": false},
  {iso:"LS",name:"Lesotho", "article": false},
  {iso:"LR",name:"Liberia", "article": false},
  {iso:"LY",name:"Libya", "article": false},
  {iso:"LI",name:"Liechtenstein", "article": false},
  {iso:"LT",name:"Lithuania", "article": false},
  {iso:"LU",name:"Luxembourg", "article": false},
  {iso:"MO",name:"Macao", "article": false},
  {iso:"MK",name:"Macedonia", "article": false},
  {iso:"MG",name:"Madagascar", "article": false},
  {iso:"MW",name:"Malawi", "article": false},
  {iso:"MY",name:"Malaysia", "article": false},
  {iso:"MV",name:"Maldives", "article": false},
  {iso:"ML",name:"Mali", "article": false},
  {iso:"MT",name:"Malta", "article": false},
  {iso:"MH",name:"Marshall Islands", "article": false},
  {iso:"MQ",name:"Martinique", "article": false},
  {iso:"MR",name:"Mauritania", "article": false},
  {iso:"MU",name:"Mauritius", "article": false},
  {iso:"YT",name:"Mayotte", "article": false},
  {iso:"MX",name:"Mexico", "article": false},
  {iso:"FM",name:"Micronesia", "article": false},
  {iso:"MD",name:"Moldova", "article": false},
  {iso:"MC",name:"Monaco", "article": false},
  {iso:"MN",name:"Mongolia", "article": false},
  {iso:"ME",name:"Montenegro", "article": false},
  {iso:"MS",name:"Montserrat", "article": false},
  {iso:"MA",name:"Morocco", "article": false},
  {iso:"MZ",name:"Mozambique", "article": false},
  {iso:"MM",name:"Myanmar [Burma]", "article": false},
  {iso:"NA",name:"Namibia", "article": false},
  {iso:"NR",name:"Nauru", "article": false},
  {iso:"NP",name:"Nepal", "article": false},
  {iso:"NL",name:"Netherlands", "article": false},
  {iso:"AN",name:"Netherlands Antilles", "article": false},
  {iso:"NC",name:"New Caledonia", "article": false},
  {iso:"NZ",name:"New Zealand", "article": false},
  {iso:"NI",name:"Nicaragua", "article": false},
  {iso:"NE",name:"Niger", "article": false},
  {iso:"NG",name:"Nigeria", "article": false},
  {iso:"NU",name:"Niue", "article": false},
  {iso:"NF",name:"Norfolk Island", "article": false},
  {iso:"KP",name:"North Korea", "article": false},
  {iso:"MP",name:"Northern Mariana Islands", "article": false},
  {iso:"NO",name:"Norway", "article": false},
  {iso:"OM",name:"Oman", "article": false},
  {iso:"PK",name:"Pakistan", "article": false},
  {iso:"PW",name:"Palau", "article": false},
  {iso:"PS",name:"Palestine", "article": false},
  {iso:"PA",name:"Panama", "article": false},
  {iso:"PG",name:"Papua New Guinea", "article": false},
  {iso:"PY",name:"Paraguay", "article": false},
  {iso:"PE",name:"Peru", "article": false},
  {iso:"PH",name:"Philippines", "article": false},
  {iso:"PN",name:"Pitcairn Islands", "article": false},
  {iso:"PL",name:"Poland", "article": false},
  {iso:"PT",name:"Portugal", "article": false},
  {iso:"PR",name:"Puerto Rico", "article": false},
  {iso:"QA",name:"Qatar", "article": false},
  {iso:"CG",name:"Republic of the Congo", "article": false},
  {iso:"RE",name:"Réunion", "article": false},
  {iso:"RO",name:"Romania", "article": false},
  {iso:"RU",name:"Russia", "article": false},
  {iso:"RW",name:"Rwanda", "article": false},
  {iso:"BL",name:"Saint Barthélemy", "article": false},
  {iso:"SH",name:"Saint Helena", "article": false},
  {iso:"KN",name:"Saint Kitts and Nevis", "article": false},
  {iso:"LC",name:"Saint Lucia", "article": false},
  {iso:"MF",name:"Saint Martin", "article": false},
  {iso:"PM",name:"Saint Pierre and Miquelon", "article": false},
  {iso:"VC",name:"Saint Vincent and the Grenadines", "article": false},
  {iso:"WS",name:"Samoa", "article": false},
  {iso:"SM",name:"San Marino", "article": false},
  {iso:"ST",name:"São Tomé and Príncipe", "article": false},
  {iso:"SA",name:"Saudi Arabia", "article": false},
  {iso:"SN",name:"Senegal", "article": false},
  {iso:"RS",name:"Serbia", "article": false},
  {iso:"CS",name:"Serbia and Montenegro", "article": false},
  {iso:"SC",name:"Seychelles", "article": false},
  {iso:"SL",name:"Sierra Leone", "article": false},
  {iso:"SG",name:"Singapore", "article": false},
  {iso:"SX",name:"Sint Maarten", "article": false},
  {iso:"SK",name:"Slovakia", "article": false},
  {iso:"SI",name:"Slovenia", "article": false},
  {iso:"SB",name:"Solomon Islands", "article": false},
  {iso:"SO",name:"Somalia", "article": false},
  {iso:"ZA",name:"South Africa", "article": false},
  {iso:"GS",name:"South Georgia and the South Sandwich Islands", "article": false},
  {iso:"KR",name:"South Korea", "article": false},
  {iso:"SS",name:"South Sudan", "article": false},
  {iso:"ES",name:"Spain", "article": false},
  {iso:"LK",name:"Sri Lanka", "article": false},
  {iso:"SD",name:"Sudan", "article": false},
  {iso:"SR",name:"Suriname", "article": false},
  {iso:"SJ",name:"Svalbard and Jan Mayen", "article": false},
  {iso:"SZ",name:"Swaziland", "article": false},
  {iso:"SE",name:"Sweden", "article": false},
  {iso:"CH",name:"Switzerland", "article": false},
  {iso:"SY",name:"Syria", "article": false},
  {iso:"TW",name:"Taiwan", "article": false},
  {iso:"TJ",name:"Tajikistan", "article": false},
  {iso:"TZ",name:"Tanzania", "article": false},
  {iso:"TH",name:"Thailand", "article": false},
  {iso:"TG",name:"Togo", "article": false},
  {iso:"TK",name:"Tokelau", "article": false},
  {iso:"TO",name:"Tonga", "article": false},
  {iso:"TT",name:"Trinidad and Tobago", "article": false},
  {iso:"TN",name:"Tunisia", "article": false},
  {iso:"TR",name:"Turkey", "article": false},
  {iso:"TM",name:"Turkmenistan", "article": false},
  {iso:"TC",name:"Turks and Caicos Islands", "article": false},
  {iso:"TV",name:"Tuvalu", "article": false},
  {iso:"UM",name:"U.S. Minor Outlying Islands", "article": false},
  {iso:"VI",name:"U.S. Virgin Islands", "article": false},
  {iso:"UG",name:"Uganda", "article": false},
  {iso:"UA",name:"Ukraine", "article": false},
  {iso:"AE",name:"United Arab Emirates", "article": false},
  {iso:"GB",name:"United Kingdom", "article": false},
  {iso:"US",name:"United States", "article": true},
  {iso:"UY",name:"Uruguay", "article": false},
  {iso:"UZ",name:"Uzbekistan", "article": false},
  {iso:"VU",name:"Vanuatu", "article": false},
  {iso:"VA",name:"Vatican City", "article": false},
  {iso:"VE",name:"Venezuela", "article": false},
  {iso:"VN",name:"Vietnam", "article": false},
  {iso:"WF",name:"Wallis and Futuna", "article": false},
  {iso:"EH",name:"Western Sahara", "article": false},
  {iso:"YE",name:"Yemen", "article": false},
  {iso:"ZM",name:"Zambia", "article": false},
  {iso:"ZW",name:"Zimbabwe", "article": false}
]
