export default {
  googleNewsLabLogo: require('../../images/google-news-lab-logo.svg'),
  hamburgerMenu: require('../../images/hamburger-menu.svg'),
  close: require('../../images/close.svg'),
  cough: require('../../images/cough.svg'),
  skinrash: require('../../images/skinrash.svg'),
  lung: require('../../images/lung.svg'),
  heart: require('../../images/heart.svg'),
  brain: require('../../images/brain.svg'),
  cell: require('../../images/cell.svg'),
  vaccine: require('../../images/vaccine.svg'),
  temperature: require('../../images/temperature.svg'),
  soap: require('../../images/soap.svg'),
  acne: require('../../images/acne.svg'),
  cream: require('../../images/cream.svg'),
  tea: require('../../images/tea.svg'),
  headache: require('../../images/headache.svg'),
  blood: require('../../images/blood.svg'),
  bacteria: require('../../images/bacteria.svg'),
  hormone: require('../../images/hormone.svg'),
  polen: require('../../images/polen.svg'),
  itch: require('../../images/itch.svg'),
  medicine: require('../../images/medicine.svg'),
  virus: require('../../images/virus.svg'),
  dizziness: require('../../images/dizziness.svg'),
  play: require('../../images/play.svg'),
}
